services:
  - type: web
    name: iot4all-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: iot4all-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d

databases:
  - name: iot4all-db
    databaseName: iot4all
    user: iot4all
